# Generated by Django 5.2.3 on 2025-07-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somos_dogs', '0003_course_alter_race_name_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
