# Generated by Django 5.2.3 on 2025-07-17 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somos_dogs', '0004_course_status_session_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='somos_dogs.dog'),
        ),
        migrations.AlterField(
            model_name='human',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human', to=settings.AUTH_USER_MODEL),
        ),
    ]
