# Generated by Django 5.2.3 on 2025-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somos_dogs', '0005_course_dog_alter_human_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
