# Generated by Django 5.2.3 on 2025-07-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somos_dogs', '0006_dog_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
