# Generated by Django 5.2.3 on 2025-07-29 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somos_dogs', '0007_user_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='somos_dogs.course')),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='somos_dogs.dog')),
            ],
        ),
    ]
