# Generated by Django 5.2.3 on 2025-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somos_dogs', '0008_remove_course_dog_remove_course_status_courseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
