# Generated by Django 5.2.3 on 2025-08-12 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somos_dogs', '0009_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='human',
        ),
        migrations.AddField(
            model_name='session',
            name='human',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
